---
title: "Temporal Models and Figures"
author: "Julia Briand"
date: "1/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lme4)
library(nlme)
library(Matrix)
library(broom.mixed)
library(MuMIn)
library(lmerTest)
library(merTools)
```

## Read in Multivariate Regression Tree groups

```{r}
trait_grp <- read.csv("trait_mrt_grps.csv")
benth_grp <- read.csv("benth_mrt_grps.csv")
coral_grp <- read.csv("coral_mrt_grps.csv")

trait_grp <- trait_grp %>% 
  mutate(Site = mrt_sites, MRT = trait.mvpart.g) %>% 
  dplyr::select(-c(mrt_sites,trait.mvpart.g))

benth_grp <- benth_grp %>% 
  mutate(Site = X, MRT = benth.mvpart.g) %>% 
  dplyr::select(-c(X,benth.mvpart.g))

coral_grp <- coral_grp %>% 
  mutate(Site = X, MRT = coral.mvpart.g) %>% 
  dplyr::select(-c(X,coral.mvpart.g))
```

## Join groups with PCoA Scores

```{r}
# Corals
corals <- read.csv("Corals_PCoA.csv")

c_tib <- as_tibble(corals)
c_tib <- c_tib %>% mutate(Reef=recode(Group, `1` = "forereef", `2` = "lagoonal"))
c_tib$Reef <- as.factor(c_tib$Reef)
c_tib <- left_join(c_tib, coral_grp)
c_tib <- c_tib %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3", `4` = "node4"))
c_tib$MRT <- as.factor(c_tib$MRT)

# Benthic
benthic <- read.csv("Taxa_PCoA.csv")

b_tib <- as_tibble(benthic)
b_tib <- b_tib %>% mutate(Reef=recode(Group, `1` = "forereef", `2` = "lagoonal"))
b_tib$Reef <- as.factor(b_tib$Reef)
b_tib <- left_join(b_tib, benth_grp)
b_tib <- b_tib %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3"))
b_tib$MRT <- as.factor(b_tib$MRT)

# Traits
traits <- read.csv("Trait_MFA.csv")

t_tib <- as_tibble(traits)
t_tib <- t_tib %>% mutate(Reef=recode(Alternate, `2` = "forereef", `1` = "lagoonal"))
t_tib$Reef <- as.factor(t_tib$Reef)
t_tib <- left_join(t_tib, trait_grp)
t_tib <- t_tib %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3", `4` = "node4"))
t_tib$MRT <- as.factor(t_tib$MRT)
```

## Run PCoA1 temporal models

# Coral

```{r}
# Random Intercept
c1 <- lme4::lmer(MDS1 ~ Year*MRT + (1|MRT/Site), data = c_tib)
summary(c1)
summary(as_lmerModLmerTest(c1))

# No Interaction Term
c2 <- lme4::lmer(MDS1 ~ Year+MRT + (1|MRT/Site), data = c_tib)
summary(c2)
summary(as_lmerModLmerTest(c2))

# Anova
anova(c1, c2)

#lme
lmec1 <- lme(fixed = MDS1~Year*MRT, random = ~ 1|MRT/Site,data=c_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(c_tib, nesting(MRT, Site), Year) 
pred<-predict(lmec1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, c_tib)

p1_c <- ggplot(fitted_pred, aes(Year, fit, group = MRT)) + geom_path(size = 0.8)+geom_point(aes(Year, MDS1, color = Reef, shape = MRT),c_tib, size = 2.5)+geom_path(aes(Year, MDS1, group= Site, color = Reef),c_tib[!is.na(c_tib$MDS1),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) +
  labs(x = "Year", y = "PCoA 1")+facet_wrap(~ MRT,scales='free') + ylim(-2.0, 2.0)+theme(legend.position = "none")
  
ggsave("pcoa1_coral_mrt.pdf", height=7, width=7.17)
```

# Benthic

```{r}
# Random Intercept
b1 <- lme4::lmer(MDS1 ~ Year*MRT + (1|MRT/Site), data = b_tib)
summary(b1)
summary(as_lmerModLmerTest(b1))

# No Interaction Term
b2 <- lme4::lmer(MDS1 ~ Year+MRT + (1|MRT/Site), data = b_tib)
summary(b2)
summary(as_lmerModLmerTest(b2))

# Anova
anova(b1, b2)

#lme
lmeb1 <- lme(fixed = MDS1~Year*MRT, random = ~ 1|MRT/Site,data=b_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(b_tib, nesting(MRT, Site), Year) 
pred<-predict(lmeb1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, b_tib)

p1_b <- ggplot(fitted_pred, aes(Year, fit, group = MRT)) + geom_path(size = 0.8)+geom_point(aes(Year, MDS1, color = Reef, shape = MRT),b_tib, size = 2.5)+geom_path(aes(Year, MDS1, group= Site, color = Reef),b_tib[!is.na(b_tib$MDS1),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) + geom_path() + labs(x = "Year", y = "PCoA 1")+
  facet_wrap(~ MRT,scales='free') + ylim(-2.0, 2.0) +theme(legend.position = "none")

ggsave("pcoa1_benth_mrt.pdf", height=4.5, width=14)
```

# Traits

```{r}
# Random Intercept
t1 <- lme4::lmer(Dim.1 ~ Year*MRT + (1|MRT/Site), data = t_tib)
summary(t1)
summary(as_lmerModLmerTest(t1))

# No Interaction Term
t2 <- lme4::lmer(Dim.1 ~ Year+MRT + (1|MRT/Site), data = t_tib)
summary(t2)
summary(as_lmerModLmerTest(t2))

# Anova
anova(t1, t2)

#lme
lmet1 <- lme(fixed = Dim.1~Year*MRT, random = ~ 1|MRT/Site,data=t_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(t_tib, nesting(MRT, Site), Year) 
pred<-predict(lmet1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, t_tib)

p1_t <- ggplot(fitted_pred, aes(Year, fit)) + geom_path(size = 0.8)+geom_point(aes(Year, Dim.1, color = Reef, shape = MRT),t_tib, size = 2.5)+geom_path(aes(Year, Dim.1, group= Site, color = Reef),t_tib[!is.na(t_tib$Dim.1),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) + labs(x = "Year", y = "MFA 1")+
  facet_wrap(~ MRT,scales='free') + ylim(-6.0, 6.0) +theme(legend.position = "none")

ggsave("pcoa1_trait_mrt.pdf", height=7, width=7.17)
```

## PCOA2 Models

# Coral

```{r}
# Corals

# Random Intercept
c1 <- lme4::lmer(MDS2 ~ Year*MRT + (1|MRT/Site), data = c_tib)
summary(c1)
summary(as_lmerModLmerTest(c1))

# No Interaction Term
c2 <- lme4::lmer(MDS2 ~ Year+MRT + (1|MRT/Site), data = c_tib)
summary(c2)
summary(as_lmerModLmerTest(c2))

# Anova
anova(c1, c2)

#lme
lmec1 <- lme(fixed = MDS2~Year*MRT, random = ~ 1|MRT/Site,data=c_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(c_tib, nesting(MRT, Site), Year) 
pred<-predict(lmec1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, c_tib)

p2_c <- ggplot(fitted_pred, aes(Year, fit, group = MRT)) + geom_path(size = 0.8)+geom_point(aes(Year, MDS2, color = Reef, shape = MRT),c_tib, size = 2.5)+geom_path(aes(Year, MDS2, group= Site, color = Reef),c_tib[!is.na(c_tib$MDS2),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + labs(x = "Year", y = "PCoA 2")+ scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) +theme(legend.position = "none") + facet_wrap(~ MRT,scales='free') + ylim(-2.5, 2.5) 

ggsave("pcoa2_coral_mrt.pdf", height=8.5, width=10.75)
```

# Benthic

```{r}
# Random Intercept
b1 <- lme4::lmer(MDS2 ~ Year*MRT + (1|MRT/Site), data = b_tib)
summary(b1)
summary(as_lmerModLmerTest(b1))

# No Interaction Term
b2 <- lme4::lmer(MDS2 ~ Year+MRT + (1|MRT/Site), data = b_tib)
summary(b2)
summary(as_lmerModLmerTest(b2))

# Anova
anova(b1, b2)

#lme
lmeb1 <- lme(fixed = MDS2~Year*MRT, random = ~ 1|MRT/Site,data=b_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(b_tib, nesting(MRT, Site), Year) 
pred<-predict(lmeb1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, b_tib)

p2_b <- ggplot(fitted_pred, aes(Year, fit, group = MRT)) + geom_path(size = 0.8)+geom_point(aes(Year, MDS2, color = Reef, shape = MRT),b_tib, size = 2.5)+geom_path(aes(Year, MDS2, group= Site, color = Reef),b_tib[!is.na(b_tib$MDS2),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + labs(x = "Year", y = "PCoA 2")+scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) +theme(legend.position = "none")+
  facet_wrap(~ MRT,scales='free') + ylim(-2.0, 2.0) 

ggsave("pcoa2_benth_mrt.pdf", height=4.5, width=15)
```

# Traits

```{r}
# Random Intercept
t1 <- lme4::lmer(Dim.2 ~ Year*MRT + (1|MRT/Site), data = t_tib)
summary(t1)
summary(as_lmerModLmerTest(t1))

# No Interaction Term
t2 <- lme4::lmer(Dim.2 ~ Year+MRT + (1|MRT/Site), data = t_tib)
summary(t2)
summary(as_lmerModLmerTest(t2))

# Anova
anova(t1, t2)

#lme
lmet1 <- lme(fixed = Dim.2~Year*MRT, random = ~ 1|MRT/Site,data=t_tib,na.action=na.omit)

# taxonomic c1
newdata <- tidyr::expand(t_tib, nesting(MRT, Site), Year) 
pred<-predict(lmet1, newdata, level=0, se.fit=T) # stick with just random intercept?
fitted_pred<-newdata %>%
  mutate(fit=pred$fit) %>%
  mutate(fit_se=pred$se.fit)

fitted_pred <- left_join(fitted_pred, t_tib)

p2_t <- ggplot(fitted_pred, aes(Year, fit)) + geom_path(size = 0.8)+geom_point(aes(Year, Dim.2, color = Reef, shape = MRT),t_tib, size = 2.5)+geom_path(aes(Year, Dim.2, group= Site, color = Reef),t_tib[!is.na(t_tib$Dim.2),], size = 0.7)+
  geom_ribbon( aes(ymin = fit-1.96*fit_se, ymax = fit+1.96*fit_se, fill = MRT), fitted_pred, alpha = .5)+
  ggthemes::theme_base() + labs(x = "Year", y = "MFA 2")+scale_fill_manual(values=c("#FEB24C", "#FF4500", "#FF4500", "#FF4500")) + geom_path() + 
  scale_color_manual(values=c("#FEB24C", "#FF4500")) + scale_shape_manual(values=c(15, 16, 17, 18)) +theme(legend.position = "none")+
  facet_wrap(~ MRT,scales='free') + ylim(-6.0, 6.0) 

ggsave("pcoa2_trait_mrt.pdf", height=4.5, width=15)
```

## Diversity Models

```{r}
# Read in diversity for each site every year
Div <- read.table("TD_FD_Sites",sep=",",header=T)
Div <- Div[,-1]
div_tib <- as_tibble(Div)
div_tib <- div_tib %>% mutate(Reef=recode(Alternate, `1` = "lagoonal", `2` = "forereef"))
div_tib$Reef <- as.factor(div_tib$Reef)

b_div <- left_join(div_tib, benth_grp)
b_div <- b_div %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3"))
b_div$MRT <- as.factor(b_div$MRT)

t_div <- left_join(div_tib, trait_grp)
t_div <- t_div %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3", `4` = "node4"))
t_div$MRT <- as.factor(t_div$MRT)

c_div <- left_join(div_tib, coral_grp)
c_div <- c_div %>% mutate(MRT=recode(MRT, `1` = "node1", `2` = "node2", `3` = "node3", `4` = "node4"))
c_div$MRT <- as.factor(c_div$MRT)
```

